from .limesurveyrc2api import LimeSurveyRemoteControl2API, LimeSurveyError
# Lifts the class into the package namespace instead of package.module
# Otherwise you'd need from limesurveyrc2api.limesurveyrc2api import Lime...
